name: klib x86

on:
  workflow_dispatch:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: '${{github.workspace}}/klib-x86'

      - name: getting klib
        uses: actions/checkout@v3
        with:
          repository: itzandroidtab/klib
          ref: 'master'
          fetch-depth: '1'
          path: '${{github.workspace}}/klib'

      - name: downloading catch2
        run: wget -q -O ${{github.workspace}}/klib-x86/catch.hpp https://github.com/catchorg/Catch2/releases/download/v2.13.10/catch.hpp

      - name: gcc version
        run: gcc --version
      
      - name: Configure CMake
        run: CC=gcc CXX=g++ cmake ${{github.workspace}}/klib-x86 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Run tests
        run: ${{github.workspace}}/build/klib-x86
